modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License v3.0 or later"

[[mods]]
modId="aforce"
version="${version}"
displayName="Advanced Forcefields"
logoFile="aforce.png"
credits="Code and textures by Slimeist, pipe models and shape code to vazkii's Quark mod, GUI element classes and network classes (com.slimeist.aforce.client.gui.ie_elements, com.slimeist.aforce.common.network) to BluSunrize, com.slimeist.aforce.common.tiles.helpers.SimpleForceModifierSelector#validForEntity to BluSunrize, com.slimeist.aforce.core.util.MobHelper to P3pp3rF1y from Reliquary"
authors="Slimeist"
description='''
Advanced Forcefields creates modular, configurable forcefields!
'''

[[dependencies.aforce]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aforce]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"
