modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"

[[mods]]
modId="aforce"
version="${version}"
displayName="Advanced Forcefields"
#logoFile="examplemod.png"
credits="Code and textures by Slimeist, pipe models and shape code to vazkii's Quark mod, GUI element classes and network classes (com.slimeist.aforce.client.gui.ie_elements, com.slimeist.aforce.common.network) to BluSunrize, com.slimeist.aforce.common.tiles.helpers.ForceModifierSelector#validForEntity to BluSunrize"
authors="Slimeist"
description='''
Advanced Forcefields are fun
'''

[[dependencies.aforce]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aforce]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
